parameters:
  logger_path: OxidEsales\EshopCommunity\Internal\Logger

services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerConfigurationValidatorInterface:
    class: %logger_path%\Validator\PsrLoggerConfigurationValidator
  OxidEsales\EshopCommunity\Internal\Logger\Validator\Configuration\MonologConfigurationInterface:
    class: %logger_path%\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'OXID Logger'
      $context: '@OxidEsales\EshopCommunity\Internal\Utility\ContextInterface'
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerFactoryInterface:
    class: %logger_path%\Factory\MonologLoggerFactory
  Monolog\Logger:
    class: Monolog\Logger
    factory: 'OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerFactoryInterface:create'
  Psr\Log\LoggerInterface:
    class: %logger_path%\Wrapper\LoggerWrapper
    arguments:
      $logger: '@Monolog\Logger'
    public: true